language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer selfupdate --no-progress
  - travis_retry composer install --prefer-dist
  - mkdir tests/temp

script:
  - vendor/bin/tester tests -C

notifications:
  email: false
