language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer selfupdate --no-progress
  - travis_retry composer install --prefer-dist

script:
  - vendor/bin/tester tests -C

notifications:
  email: false
